version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_ENV=development
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t /app

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_ENV=development
      - WORKER_NAME=worker-${WORKER_NUM:-1}
    depends_on:
      redis:
        condition: service_healthy
    command: php 03-ml-worker.php
    restart: unless-stopped

volumes:
  redis_data:

